name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-portfolio || exit 1

            git pull origin master

            docker stop frontend-container || true
            docker rm frontend-container || true
            docker stop backend-container || true
            docker rm backend-container || true

            docker build -t portfolio-backend ./backend
            docker build -t portfolio-frontend ./frontend

            docker run -d \
              --name backend-container \
              -p 4000:4000 \
              portfolio-backend

            docker run -d \
              --name frontend-container \
              -p 80:80 \
              portfolio-frontend
