name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------------- FRONTEND ----------------
      - name: Build Frontend Image
        run: |
          docker build -t portfolio-frontend ./frontend

      # ---------------- BACKEND ----------------
      - name: Build Backend Image
        run: |
          docker build -t portfolio-backend ./backend

      # ---------------- DEPLOY ON SERVER ----------------
      - name: Deploy on Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker stop backend-container || true
            docker rm backend-container || true

            docker run -d \
              --name backend-container \
              -p 4000:4000 \
              portfolio-backend

            docker run -d \
              --name frontend-container \
              -p 80:80 \
              portfolio-frontend
